### ISSUE TITLE
勋章加载不出来

### ISSUE THREAD

**Issue by woshiliuxu** [Lemon-cxh/pwl-chat-extension#1]
![image](https://user-images.githubusercontent.com/58692858/154229660-3ea7f4fa-a565-47db-aa95-a6249d1a5789.png)

版本 ：1.0.9

**Comment by Lemon-cxh** [comment]
这个问题摸鱼派服务器已更新
[感谢@teahouse15，勋章渲染本地化](https://github.com/csfwff/rhythm/commit/a3131d68beb48274ed2cff5668c361a426172dbc)
