### ISSUE TITLE
网页端插件问题

### ISSUE THREAD

**Issue by qq1176914912** [Lemon-cxh/pwl-chat-extension#6]
当你在输入框输入完字之后，在选择表情，他就会复制你前面的所有字比如，我输入123，然后选个表情，他就会变成这样
![image](https://github.com/Lemon-cxh/pwl-chat-extension/assets/79817742/ea11730c-9456-4c34-a2aa-ce442809d0b9)
如果继续选择表情，那么就会继续复制输入框中存在的内容，基本就是数量从1变2 2变4这种
粘贴也会这样，输入123然后ctrl+v粘贴，也会复制已经输入了的内容

**Comment by Lemon-cxh** [comment]
感谢反馈，已修复
